language: node_js
node_js:
  - "0.8"
  - "0.10"
after_script:
  - make update-coverage
env:
  global:
    # ECHONEST_API_KEY
    - secure: "TmUR560Jm6Rc8K5zoEVskER3h4Evkf/Db7JHArfY33sXW57XOe6i9IKLedRUEf3I0/VIyHNt0oyv2A8w0kllisVtILAdg2adGKflWJzqeP0XWEaVPATgodLO8TUPDCVQV5OX662UR6t9YkY8XaOrZYDoHUxhqzcf4YV5LdKQO8Q="
